
# Code Snippets
DESTDIR=~/Library/Developer/Xcode/UserData/CodeSnippets
CODESNIPPETSDIR=CodeSnippets
SETUP_SNIPPET=4DA65AE7-2FD0-4F79-842B-14FBB42E31D2.codesnippet
TEARDOWN_SNIPPET=9C175617-CE05-4BCA-848D-C4E4DAC19851.codesnippet
TESTCASE_SNIPPET=96593CA0-9F64-4AAC-BAD0-1E77F6120775.codesnippet
HAMCREST_IOS_SNIPPET=D67E10C5-67EF-46D8-8335-5B5DEA875BCF.codesnippet
HAMCREST_OSX_SNIPPET=D3B7BE53-9A14-42F8-94D9-6B273C29B338.codesnippet
MOCKITO_IOS_SNIPPET=1C2FBA6C-FA44-4408-AE45-F6071D31F4FA.codesnippet
MOCKITO_OSX_SNIPPET=CF8330B7-AA6D-48C7-96AD-20F7C943B51B.codesnippet
OUTLET_SNIPPET=05CE602B-A281-4B4C-80A2-4F3A9C4E6902.codesnippet
BUTTON_ACTION_SNIPPET=17D94DE5-BC5B-49F6-9697-E1D2FE4A354B.codesnippet

# Templates
DESTDIR=~/Library/Developer/Xcode/Templates/File\ Templates
IOSTEMPLATE=Templates
IOSDESTDIR=$(DESTDIR)/Cocoa\ Touch


install:
	mkdir -p $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(SETUP_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(TEARDOWN_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(TESTCASE_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(HAMCREST_IOS_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(HAMCREST_OSX_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(MOCKITO_IOS_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(MOCKITO_OSX_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(OUTLET_SNIPPET) $(DESTDIR)
	cp $(CODESNIPPETSDIR)/$(BUTTON_ACTION_SNIPPET) $(DESTDIR)

	mkdir -p $(IOSDESTDIR)
	cp -R $(IOSTEMPLATE) $(IOSDESTDIR)

uninstall:
	rm $(DESTDIR)/$(SETUP_SNIPPET)
	rm $(DESTDIR)/$(TEARDOWN_SNIPPET)
	rm $(DESTDIR)/$(TESTCASE_SNIPPET)
	rm $(DESTDIR)/$(HAMCREST_IOS_SNIPPET)
	rm $(DESTDIR)/$(HAMCREST_OSX_SNIPPET)
	rm $(DESTDIR)/$(MOCKITO_IOS_SNIPPET)
	rm $(DESTDIR)/$(MOCKITO_OSX_SNIPPET)
	rm $(DESTDIR)/$(OUTLET_SNIPPET)
	rm $(DESTDIR)/$(BUTTON_ACTION_SNIPPET)

	rm -rf $(IOSDESTDIR)/$(IOSTEMPLATE)